### ISSUE TITLE
[Feat] 리포트 기능추가

### ISSUE THREAD

**Issue by Wegbereiterin** [APP-iOS3rd/PJ4T5_TrackUs#56]
## Feature
추가 예정인 기능에 대하여 설명해주세요.

리포트에 들어갈 기능을 추가

## Todo
여러개의 기능이 추가될 예정이라면 카테고리를 나눠주세요.

### Feature1
- [x] 파이어스토어 데이터 가져오기 (Read)
- [x] 가져온 데이터로 리포트에서 잘 보여주게끔 기능 추가
- [x] 일별, 월별 데이터 보여주기
- [x] 원그래프(progress) 기능
- [x] 날짜별, 월별 운동량 그래프 (horizontal) 기능
- [x] 평균 운동량 추세 바 그래프, 꺾은선 그래프 기능
