### ISSUE TITLE
[Refactor] 라이브트래킹 코드 리펙토링

### ISSUE THREAD

**Issue by kwon-seokki** [APP-iOS3rd/PJ4T5_TrackUs#64]
## 내용
라이브트래킹 관련 코드 리펙토링

## TODO
- [x] 트래킹 뷰모델 리펙토링
- [ ] 라이브트래킹 데이터 필터링
- [x] 운동정보 계산로직 리펙토링
- [x] 단위변환 포매팅 
- [x] 디자인파일 코드스타일 리펙토링
