### ISSUE TITLE
[Feat] 러닝기록 데이터에 러닝이름 추가

### ISSUE THREAD

**Issue by kwon-seokki** [APP-iOS3rd/PJ4T5_TrackUs#67]
## Feature
러닝기록에 러닝이름을 별도로 지정할 수 있는 기능(팝업 형식으로 입력)

## Todo
여러개의 기능이 추가될 예정이라면 카테고리를 나눠주세요.

### 러닝이름 입력UI
- [x] 러닝이름 입력할 수 있는 팝업 구현

### 러닝이름 데이터 추가
- [x] DB에 러닝이름 데이터 추가하도록 구현
- [x] DB에 러닝시작위치 한글로 저장
