### ISSUE TITLE
[Feat] ChattingView 추가

### ISSUE THREAD

**Issue by Choe-ju** [APP-iOS3rd/PJ4T5_TrackUs#68]
## Feature
- 채팅 관련 view, viewModel추가
- 이후 firebase 연결

## Todo
여러개의 기능이 추가될 예정이라면 카테고리를 나눠주세요.

### View
- [x] 채팅창 UI
- [x] 사이드 메뉴
- [x] 채팅 List
  - [x] UI 수정 

### ViewModel
- [ ] 사진 촬영 전송
- [ ] 라이브러리 사진 전송
- [x] 그룹, 1:1 채팅 생성 or 참여하기
- [x] 채팅방 나가기
- [x] 채팅방 실시간 업데이트

### Model
- [x] 채팅방 정보
- [x] 채팅 message
---
### 확장
- [x] 1:1 대화방 -> title 부분 로직 설정
- [x] 그룹 채팅
